### ISSUE TITLE
Test does not pass without express

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/angular-multiple-directives-lab#2]
Test needs express installed and there are no instructions for installing it for this lab.

**Comment by mendelB** [comment]
@ipc103 @PeterBell @aturkewi #3 
Running 'learn' after running the 'npm install -g express' with the global flag still returned an error, running 'npm install express' made things work. (adding a package.json with an express dependency and npm installing also worked for me)

**Comment by PeterBell** [comment]
Hey @ipc103 just want to check in on this. Do we _really_ want to install express globally? Feel like that's gonna get us in a world of hurt if/when different labs depend on different versions of express that aren't compatible. How about we reverse this out and add a packge.json so we use NPM. Thoughts? cc @pletcher

**Comment by pletcher** [comment]
I think we should go with the `package.json` approach. If the goal is that students have the express generator available, I believe the current best practice is to `npm install express-generator -g`.

**Comment by ipc103** [comment]
sounds good to me - i'll roll this back and add the package.json file

On Mon, Mar 21, 2016 at 11:48 AM, Charles Pletcher <notifications@github.com

> wrote:
> 
> I think we should go with the package.json approach. If the goal is that
> students have the express generator available, I believe the current best
> practice is to npm install express-generator -g.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/learn-co-curriculum/angular-multiple-directives-lab/issues/2#issuecomment-199349089

## 

```
 Ian Candy
 Web Instructor
```
